version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: example
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      CONNECT_URL: "postgres://postgres:@db:5432/example?sslmode=disable"
    volumes:
      - .:/app

volumes:
  postgres:
